# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: 'Wait'

description: 'Wait a designated number of milliseconds'

inputs:
  milliseconds:  #id
    description: 'number of millisecond to wait'
    required: true
    default: '1000'
  outputs:
    time: #output will be available to future steps
      description: 'The message to output'
runs:
  using: 'node12'
  main: 'index.js'