

name: Java CI with gradle
run-name: Build by ${{ github.actor }} 🧬🚀💻🛠
on:
#  push:
#    branches: [develop]
  pull_request:
#    branches: [develop]
    branches: [build]

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17.0.1

      - name: Read value from properties file
        id: read_property
        uses: christian-draeger/read-properties@1.1.0
        with:
          path: 'version.properties'
          properties: 'buildNumber'
      - name: Do something with your bumped release version
        run: echo ${{ steps.read_property.outputs.buildNumber}}

      - name: Add & Commit

        uses: EndBug/add-and-commit@v9.1.1
        with:
          new_branch: build
          message: 'New Branch'
#          pull: '--rebase --autostash'

#        with:
#


#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#
#      - name: Build with gradle
#        run: ./gradlew build -Pserver

#      - name: Add & Commit
#        uses: EndBug/add-and-commit@v9.1.1
#        with:
#          pull: '--rebase --autostash'

#        run: ./gradlew build
#      - name: Increment Version
#        run: ./gradlew incrementVersion