name: Log latest release
on:
  push:
    branches:
      - release_test

jobs:
  logLatestRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_latest_release
        env:
          owner: githu.actor
          repo: GNDecorator
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: GET /repos/{$owner}/{$repo}/releases/latest
          owner: github.actor
          repo: request-action

      - run: "echo latest release: ${{ steps.get_latest_release.outputs.data }}"