#name: Log latest release
#on:
#  push:
#    branches:
#      - release_test
#jobs:
#  logLatestRelease:
#    runs-on: ubuntu-latest
#    steps:
#
##        id: get_latest_release
##        env:
##          repo: GNDecorator
##          route: GET /repos/${{github.actor}}/${{env.repo}}/releases/latest
#      #          route: GET /repos/{owner}/{repo}/releases/latest
#      #          repo: request-action
#
#      - name : 'Create Release'
#        uses: octokit/request-action@v2.x
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - name: 'Use script'
#      - uses: "actions/github-script@v5"
#        with:
#          script: |
#            await octokit.request('POST /repos/${{github.actor}}/${{env.repo}}/releases', {
#              owner: gleidsonmt,
#              repo: GNDecorator,
#              tag_name: 'v2.1.26',
#              target_commitish: 'release_test',
#              name: '${{env.repo}} v2.1.26',
#              body: 'Testing action creating release',
#              draft: false,
#              prerelease: false,
#              generate_release_notes: false
#            });

#      - run: "echo latest release: ${{ steps.get_latest_release.outputs.data }}"