name: GitHub Actions Demos
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      release_test
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: madhead/read-java-properties@latest
        id: majorVersion
        with:
          file: build.properties
          property: majorVersion
          default: 0.0.1

      - run: echo ${{ steps.majorVersion.outputs.value }}


