name: Update Version

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Read Test
      - uses: madhead/read-java-properties@latest
        id: version
        with:
          file: build.properties
          property: majorVerion
          default: 0.0.1
      - run: echo ${{ steps.version.outputs.value }}
