name: GitHub Actions Demos
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      [release_test]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17.0.1
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
#      - name: Build with gradle
#        run: ./gradlew build
      - name: Increment Version
        run: ./gradlew incrementVersion


